version: '3'
services:
  db:
    image: mariadb
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  dbClient:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      PMA_HOST: db
    ports:
      - 8085:80
    depends_on:
      - db

  web:
    image: nginx:1.19.1-alpine
    restart: always
    volumes:
      - ../code/static:/var/www/html/public
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/blog.conf:/etc/nginx/sites-enabled/blog.conf
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./nginx/log:/var/log/nginx
    ports:
      - 8080:8000
    depends_on:
      - python

  python:
    build: ./python
    restart: always
    volumes:
      - ../code:/code
    # requeired to set up command in pipenv script
    command: > 
      sh -c '
      pipenv install --system &&
      uwsgi --socket :8000 --module project.wsgi
      '
    depends_on:
      - db
