version: '3'
services:
  web:
    image: nginx:1.19.1-alpine
    restart: always
    volumes:
      - ../code/static:/var/www/html/public
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/blog.conf:/etc/nginx/sites-enabled/blog.conf
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./nginx/log:/var/log/nginx
    ports:
      - 8080:8000
    depends_on:
      - python

  python:
    build: ./python
    restart: always
    volumes:
      - ../code:/code
    command: > 
      sh -c '
      pipenv install --system --ignore-pipfile --deploy &&
      uwsgi --socket :8000 --module project.wsgi
      '
