version: '3'
services:
  db:
    image: mariadb
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: blog

  dbClient:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      PMA_HOST: db
    ports:
      - 8085:80
    depends_on:
      - db

  python:
    depends_on:
      - db
